[package]
name = "siglus-decompile"
version = "0.1.0"
authors = ["bluecookies <landentire@gmail.com>"]

[dependencies]
getopts = "0.2"
byteorder = "1"
log = "0.4"
fern = "0.5"
itertools = "0.7.8"
petgraph = "0.4.12"